#
# Makefile for the kernel Jet device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_BT_GPIO)		+= btgpio/
obj-$(CONFIG_CMM)		+= cmm/
obj-$(CONFIG_DPRAM)		+= dpram/
#obj-$(CONFIG_DPRAM_RECOVERY)		+= dpram_recovery/
obj-$(CONFIG_G2D)		+= g2d/
obj-$(CONFIG_G3D)		+= g3d/
obj-$(CONFIG_JPEG)		+= jpeg/
obj-$(CONFIG_MFC)		+= mfc/
obj-$(CONFIG_MULTIPDP)		+= multipdp/
#obj-$(CONFIG_PARAM)		+= param/
obj-$(CONFIG_PP)		+= pp/
#obj-$(CONFIG_RFS_FS)		+= rfs/
#obj-$(CONFIG_ROTATOR)		+= rotator/
obj-$(CONFIG_VIBETONZ)		+= vibetonz/
obj-$(CONFIG_WLAN)		+= wlan/
#obj-$(CONFIG_RFS_XSR)		+= xsr/
#obj-$(CONFIG_CAMERA)		+= camera/
obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
#obj-$(CONFIG_JPEG_V2)		+= jpeg_v2/
obj-$(CONFIG_VIDEO_SCALER)      += scaler/
obj-$(CONFIG_VIDEO_TVOUT)	+= tvout/
obj-$(CONFIG_VIDEO_TSI)		+= tsi/


