#
# Makefile for the kernel multimedia device drivers.
#

obj-y += common/ video/

obj-$(CONFIG_VIDEO_DEV)		+= radio/
obj-$(CONFIG_DVB_CORE)  	+= dvb/
#obj-$(CONFIG_VIDEO_BTGPIO)	+= s3c6410/btgpio/
#obj-$(CONFIG_VIDEO_SAMSUNG)	+= s3c6410/camera/
#obj-$(CONFIG_S3C_CMM)       	+= s3c6410/cmm/
#obj-$(CONFIG_VIDEO_G2D)     	+= s3c6410/g2d/
#obj-$(CONFIG_VIDEO_G3D)     	+= s3c6410/g3d/
#obj-$(CONFIG_VIDEO_JPEG) 	+= s3c6410/jpeg/
#obj-$(CONFIG_VIDEO_MFC)		+= s3c6410/mfc/
#obj-$(CONFIG_VIDEO_MULTIPDP)	+= s3c6410/multipdp/
#obj-$(CONFIG_VIDEO_PARAM)	+= s3c6410/param/
#obj-$(CONFIG_VIDEO_PP)		+= s3c6410/pp/
#obj-$(CONFIG_VIDEO_ROTATOR)	+= s3c6410/rotator/
#obj-$(CONFIG_VIDEO_VIBETONZ)	+= s3c6410/vibetonz/
#obj-$(CONFIG_VIDEO_WLAN)	+= s3c6410/wlan/
