obj-$(CONFIG_MFC)		+= mfc/
obj-$(CONFIG_POST)		+= post/
obj-$(CONFIG_ROTATOR)		+= rotator/
obj-$(CONFIG_JPEG)		+= jpeg/
obj-$(CONFIG_G2D)		+= g2d/
obj-$(CONFIG_G3D)		+= g3d/
obj-$(CONFIG_CMM)		+= cmm/
obj-$(CONFIG_BT_GPIO)		+= btgpio/
obj-$(CONFIG_CAMERA)		+= camera/
obj-$(CONFIG_RFS_XSR)		+= xsr/
obj-$(CONFIG_DPRAM)		+= dpram/
obj-$(CONFIG_VIBETONZ)		+= vibetonz/
obj-$(CONFIG_MULTIPDP)		+= multipdp/
obj-$(CONFIG_PARAM)		+= param/
obj-$(CONFIG_RFS_FS)		+= rfs/

