##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: KyoungHOON Kim (khoonk)
##############################################################################
# VERSION&DATE	: Version 1.00	2006/06/02 (khoonk)
##############################################################################


EXTRA_CFLAGS += -I$(PRJROOT)/driver/include

obj-m := multipdp.o

#multipdp-objs := multipdp_module.o

