#
#obj-$(CONFIG_VIDEO_CAM)	+= camera/
obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_G2D)		+= g2d/
obj-$(CONFIG_VIDEO_G3D)		+= g3d/
obj-$(CONFIG_VIDEO_JPEG_V2)	+= jpeg_v2/
obj-$(CONFIG_VIDEO_MFC)		+= mfc40/
#obj-$(CONFIG_VIDEO_PP)		+= pp/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_SCALER)  += scaler/
obj-$(CONFIG_VIDEO_TSI)		+= tsi/
obj-$(CONFIG_VIDEO_TVOUT)	+= tvout/

EXTRA_CFLAGS += -Idrivers/media/video

