##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: KyoungHOON Kim (khoonk)
##############################################################################
# VERSION&DATE	: Version 1.00	2006/06/02 (khoonk)
##############################################################################


#EXTRA_CFLAGS += -I$(PRJROOT)/driver/include
EXTRA_CFLAGS += -I../xsr/Inc


obj-m := dpram.o

#dpram-objs := xsr.o xsr.mod.o

